### ISSUE TITLE
ENH: support pandas object as X, y

### ISSUE THREAD

**Issue by martinfleis** [pysal/spreg#127]
Assuming that the data we work with are most likely pandas.DataFrames, I find this pattern a bit unintuitive.

```py
spreg.OLS(
    df[["dependent"]].values,
    df[independent_names].values,
    name_y="dependent",
    name_x= independent_names,
)
```

Since the data already have names in the original data frame, I would love to see this pattern:

```py
spreg.OLS(
    df["dependent"],
    df[independent_names],
)
```
where `spreg` gets values for `name_y` and `name_x` automatically as the name of the Series and column names.

This currently fails on the `check_arrays` call.

**Comment by pedrovma** [comment]
This feature will be in the next release.

**Comment by pedrovma** [comment]
Added in #145.
