### ISSUE TITLE
Build docs failure

### ISSUE THREAD

**Issue by pedrovma** [pysal/spreg#148]
Build docs is failing to import graph [here](https://github.com/pysal/spreg/actions/runs/10601532835/job/29381510488).

@jGaboardi , could you please check what is going on?

**Comment by knaaptime** [comment]
we probably need to update the CI and the docs recipes. I don't think graph is available on python 3.9

**Comment by jGaboardi** [comment]
I won't be able to give this attention until next week at the earliest.
