### ISSUE TITLE
Add notebooks 

### ISSUE THREAD

**Issue by sjsrey** [pysal/spreg#15]
Following the [submodule template](https://github.com/pysal/submodule_template), spreg needs a notebooks directory to provide examples for users.
There is a set of [notebooks from older workshops](https://github.com/sjsrey/pysal_narsc_2015) that need to be updated for the new import schemes but could serve as candidates for the example notebooks for spreg.

**Comment by pabloestradac** [comment]
I can use a couple of notebook examples from the workshop you mention. I was thinking to start with [Spatial 2SLS](https://github.com/sjsrey/pysal_narsc_2015/blob/master/spreg/Chapter%207%20-%20Spatial%202SLS.ipynb) and [ML Error](https://github.com/sjsrey/pysal_narsc_2015/blob/master/spreg/Chapter%2010%20-%20ML%20Error.ipynb).

**Comment by jGaboardi** [comment]
There is now a `notebooks/` directory.
