### ISSUE TITLE
GM_Lag throws Singular Matrix error with high-dimension design matrix

### ISSUE THREAD

**Issue by gboeing** [pysal/spreg#23]
I'm estimating a spatial model to predict a continuous response variable (~45,000 observations) from a design matrix with 8 (relatively orthogonal) continuous predictors and ~1,390 spatial fixed effects (county dummies, with one omitted). This is pysal 2.0.0.

OLS estimation works fine:

```python
model = spreg.ols.OLS(y=Y.values, x=X.values, w=W1, spat_diag=True, moran=True)
```

As does GM_Error estimation:

```python
model = spreg.GM_Error(y=Y.values, x=X.values, w=W1)
```

However, GM_Lag estimation raises a singular matrix exception:

```python
model = spreg.GM_Lag(y=Y.values, x=X.values, w=W1)
```
```
---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
<ipython-input-29-97756ed52f49> in <module>
      1 sp_er_model1 = spreg.GM_Lag(y=Y.values, x=X.values, w=W1, name_w='W1',
----> 2                             name_x=X.columns.tolist(), name_y=response)
      3 print(sp_er_model1.pr2)
      4 print(make_pysal_table(sp_er_model1, ignore=fixed_effects))

G:\Anaconda\envs\ox\lib\site-packages\pysal\model\spreg\twosls_sp.py in __init__(self, y, x, yend, q, w, w_lags, lag_q, robust, gwk, sig2n_k, spat_diag, vm, name_y, name_x, name_yend, name_q, name_w, name_gwk, name_ds)
    472             self, y=y, x=x_constant, w=w.sparse, yend=yend2, q=q2,
    473             w_lags=w_lags, robust=robust, gwk=gwk,
--> 474             lag_q=lag_q, sig2n_k=sig2n_k)
    475         self.rho = self.betas[-1]
    476         self.predy_e, self.e_pred, warn = sp_att(w, self.y, self.predy,

G:\Anaconda\envs\ox\lib\site-packages\pysal\model\spreg\twosls_sp.py in __init__(self, y, x, yend, q, w, w_lags, lag_q, robust, gwk, sig2n_k)
    171 
    172         TSLS.BaseTSLS.__init__(self, y=y, x=x, yend=yend, q=q,
--> 173                                robust=robust, gwk=gwk, sig2n_k=sig2n_k)
    174 
    175 

G:\Anaconda\envs\ox\lib\site-packages\pysal\model\spreg\twosls.py in __init__(self, y, x, yend, q, h, robust, gwk, sig2n_k)
    156         self.k = z.shape[1]
    157         hth = spdot(h.T, h)
--> 158         hthi = la.inv(hth)
    159         zth = spdot(z.T, h)
    160         hty = spdot(h.T, y)

G:\Anaconda\envs\ox\lib\site-packages\numpy\linalg\linalg.py in inv(a)
    549     signature = 'D->D' if isComplexType(t) else 'd->d'
    550     extobj = get_linalg_error_extobj(_raise_linalgerror_singular)
--> 551     ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
    552     return wrap(ainv.astype(result_t, copy=False))
    553 

G:\Anaconda\envs\ox\lib\site-packages\numpy\linalg\linalg.py in _raise_linalgerror_singular(err, flag)
     95 
     96 def _raise_linalgerror_singular(err, flag):
---> 97     raise LinAlgError("Singular matrix")
     98 
     99 def _raise_linalgerror_nonposdef(err, flag):

LinAlgError: Singular matrix
```

Presumably, my matrix couldn't truly be singular, or I wouldn't have been able to estimate the OLS and GM_Error models, right? Maybe this has something to do with the curse of dimensionality? If I add a noise to my spatial fixed effects dummies, GM_Lag estimation works fine. But it seems odd to add noise to dummy variables just to make the matrix invertible.

This may be a known issue with an obvious explanation. Feel free to close, if so!

**Comment by ljwolf** [comment]
hmm... What's the structure of `W1`?

**Comment by ljwolf** [comment]
Yeah... I bet it's a thing with the structure of `W1`. 

The inversion fails in constructing the instrument covariance matrix ([`la.inv(hthi)` in your traceback](https://github.com/pysal/spreg/blob/master/spreg/twosls.py#L158)), so this could mean the [spatial lags of `X` may be collinear with each other, or with `X`](https://github.com/pysal/spreg/blob/master/spreg/twosls.py#L150). If X itself works in OLS, then I 5hink it's real likely that the issue lies in collinearity within the WX matrices or between the WX and X matrices...

Not sure w/o corroborating data, but I bet the fixed effects will be highly-collinear with their spatial lags if most members of each group are nearer to one another than they are to members of other groups.

**Comment by gboeing** [comment]
Thanks Levi!

**Comment by pedrovma** [comment]
My bet is on the spatial lags of the dummies. @gboeing, if you want to follow-up on this issue, you could try to run spreg.twosls.TSLS using WY as endogenous variables and WX and WWX (for all X but the dummies) as instruments. This should work as an alternative route for your model. The only thing you'll miss is the AK Test, which you could also run manually.

**Comment by gboeing** [comment]
Thanks @pedrovma. That makes sense and the estimation seems to work fine with `spreg.twosls.TSLS` and `q = np.concatenate([WX, WWX], axis=1)` (for all X columns other than the spatial fixed effects) as instruments.

Out of curiosity, is it possible to do something similar for a spatial lag + error combo model? As far as I can tell from the documentation, `spreg.GM_Combo_Het` doesn't let you use a "reduced set" of X's columns as instruments (to avoid including spatial fixed effects).

**Comment by pedrovma** [comment]
I am truly glad it worked, @gboeing! I believe you could try a similar strategy: use spreg.GM_Endog_Error_Het with `yend = WY` and

> `q = np.concatenate([WX, WWX], axis=1)` (for all X columns other than the spatial fixed effects) as instruments

Personally, I am not a huge fan of Combo models, but I really hope it works! =)

**Comment by JosiahParry** [comment]
Coming here after encountering a similar problem and wanted to provide a comment for posterity (i.e. future me).

Based on Anselin & Rey 2014 chapter 7.1.3 (p. 162/163). There are two "regularity conditions required to establish consistency and asymptotic normality." They write: 

> " ... the first regularity condition may be violated when certain indicator variables are used in the model specification, such as so-called _spatial fixed effects_." (emphasis added)

The fixed effects can lead to linear dependency between WX & X. I've also encountered this with other more simple dummy variables.

**Comment by pedrovma** [comment]
The argument `slx_vars` allows you to choose which variables will be lagged when running a model with WX (i.e. `slx_lags>0`). You can use it to exclude any dummy variable from the lag operation.
