### ISSUE TITLE
Not being able to release to PyPI using release_and_publish.yml

### ISSUE THREAD

**Issue by pedrovma** [pysal/spreg#49]
When I pushed a v.1.1.2 commit, it did update Zenodo, but not PyPI. Any help appreciated! Thanks.

**Comment by jGaboardi** [comment]
It seems that [`release_and_publish.yml`](https://github.com/pysal/spreg/blob/master/.github/workflows/release_and_publish.yml) has never actually been [triggered](https://github.com/pysal/spreg/actions?query=workflow%3Arelease_and_publish). My first thought is that you are giving a [commit message](https://github.com/pysal/spreg/commit/7146f364e96f66a40be839a80eb28acfecf1b8d1) that follows the necessary text pattern (`"v*"`), but are not actually [***tagging*** the commit](https://git-scm.com/book/en/v2/Git-Basics-Tagging). As for the Zenodo update, that is tied to the GitHub release, so it is automatically bumped even with a manual release.

**Comment by jGaboardi** [comment]
For example, `spaghetti`'s latest release was triggered by [creating the `1.5.0` tag](https://github.com/pysal/spaghetti/commit/7732008b018c63f578a2079e7c747ea6fa84b765) and pushing directly to `pysal/spaghetti`'s `master`.

**Comment by weikang9009** [comment]
It might have sth to do with setting up pypi passwords/credentials on GitHub? See [Section Saving credentials on GitHub](https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#saving-credentials-on-github)

**Comment by pedrovma** [comment]
> It might have sth to do with setting up pypi passwords/credentials on GitHub? See [Section: Saving credentials on GitHub](https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#saving-credentials-on-github)

I did add a token key to spreg: https://github.com/pysal/spreg/settings/secrets

I guess it may be the tag issue @jGaboardi mentioned. I've never worked with tags before. Maybe the best way to proceed would be to try to release a version `1.1.3`?

**Comment by jGaboardi** [comment]
I think your best bet would be to start from either `v1.1.2.post1` or `v1.1.3.rc1` and iterate up (i.e. `post2`, `post3`, ...) until it gets working ***then*** an actual `v1.1.3`. This is what @knaaptime and I did. It took [14 attempts](https://github.com/spatialucr/geosnap/pull/221#issuecomment-618147499) to get correctly in `geosnap` [13 attempts](https://github.com/pysal/spaghetti/releases/tag/v1.5.0.rc13) to get correctly in `spaghetti`.

**Comment by jGaboardi** [comment]
[`v1.1.2.post1`](https://github.com/pysal/spreg/releases/tag/v1.1.2.post1) released correctly on GH and on [pypi](https://pypi.org/project/spreg/1.1.2.post1/)! The workflow processed [successfully](https://github.com/pysal/spreg/actions/runs/198076559)!

**Comment by pedrovma** [comment]
Awesome, thank you so much.
