### ISSUE TITLE
Docstring test failures

### ISSUE THREAD

**Issue by jGaboardi** [pysal/spreg#57]
See [here](https://github.com/pysal/spreg/issues/56#issuecomment-753056349).
* infrastructure already [in place](https://github.com/pysal/spreg/tree/master/ci)
* uncomment/replace code chunk in [`.github/workflows/unittests.yml`](https://github.com/pysal/spreg/blob/master/.github/workflows/unittests.yml#L18)

**Comment by pedrovma** [comment]
Fixed in #135.
