### ISSUE TITLE
Ambiguity in the definition of Pseudo R-squared and Spatial Pseudo R-squared in spreg.GM_Lag

### ISSUE THREAD

**Issue by ale-v** [pysal/spreg#94]
The spreg.GM_Lag outputs, among other indicators, a Pseudo R-squared and a Spatial Pseudo R-squared but I cannot understand what they refer to. Is the first the total explained variance attributable to the variables and lagged versions? Is the second the explained variance only attributable to the lagged variables? The official page https://spreg.readthedocs.io/en/latest/generated/spreg.GM_Lag.html does not seem to provide clear information on this. Can anyone please shed some light?

**Comment by pedrovma** [comment]
Dear @ale-v , 

Please find below excerpts from Anselin & Rey's (2014) book that make clear what [spatial] pseudo-R^2 refers to:
<img width="612" alt="image" src="https://user-images.githubusercontent.com/4238922/173591905-8557b58b-4a1a-4322-9b67-45b932697b13.png">
<img width="600" alt="image" src="https://user-images.githubusercontent.com/4238922/173592497-20597554-7eb3-4bb4-a55e-2d4a793faad4.png">
<img width="547" alt="image" src="https://user-images.githubusercontent.com/4238922/173592577-3d3227e6-3eaf-48e2-9c53-8d0152de9bd9.png">

Best,

Pedro.

**Comment by ale-v** [comment]
Thank you! It would be probably worth updating the docs though.
